### ISSUE TITLE
Feature Request: export to YouMagine

### ISSUE THREAD

**Issue by adeebshihadeh** [CarlosGS/export-things#1]
YouMagine is made by a company that does good things for open source, but there is a lack of models on the site. It would be nice if the script was able to also export to YouMagine. GitHub is good for hosting models but it is a bit difficult for the models to be found.

**Comment by CarlosGS** [comment]
That'd be a nice function to have, but sorry I don't really have any plans on working on this further.

Youmagine has an awesome drag&drop system when creating pages, that allows to easily bring copy them from Thingiverse (the process isn't fully automated, but it is reasonably convenient in order to port designs).
